### ISSUE TITLE
puppet provide doesn't detect password changes necessary when run in local mode

### ISSUE THREAD

**Issue by woneill** [seveas/python-hpilo#100]
When running the puppet provider to manage ILO users, it appears that the password checks will always return 'true' if managing the local ILO:

```ruby
def check_password(login, password)
        begin
            @provider.hpilo_cli('-l', login, '-p', password, @hostname, 'get_fw_version')
            true
        rescue
            false
        end
end
```

I can't think of a workaround even using `hponcfg` directly in local mode that'll force require a password- appears that's the safety net that allows forgotten passwords to be reset.

**Comment by seveas** [comment]
Yes, when talking to the iLO via the kernel driver, no authentication is done and any password is accepted. Resetting forgotten passwords is one of the things that is made possible by this. This is a feature of the iLO itself and this cannot be changed. So if you want to manage passwords of the local iLO, you'll need to check them via the network interface I'm afraid.
