### ISSUE TITLE
Setting up LDAP groups is hard - most strings are "Invalid Boolean" ;)

### ISSUE THREAD

**Issue by pomac303** [seveas/python-hpilo#101]
Doing:
import hpilo
ilo = hpilo.Ilo(somehost, user, passw)

try:
    ilo.mod_dir_config(dir_grpacct6_name, valid_ldap_path)
except hpilo.IloError as e:
    print('Failed ' + e.message)

will state "Invalid Boolean"

**Comment by seveas** [comment]
You're using the API wrong. You should specify key=value parameters, e.g. `mod_dir_config(dir_grpacct6_name='....')`

**Comment by pomac303** [comment]
Yes, you're right - sorry
