### ISSUE TITLE
LDAP group privs matching

### ISSUE THREAD

**Issue by pomac303** [seveas/python-hpilo#102]
While the permissions of groups will typically look like this:
"login,oemhp_rc,oemhp_vm,oemhp_power,config,admin"

you want: "1,2,3,4,5" without a mapping table that gives you information about which is which

**Comment by seveas** [comment]
the 1,2,3,4,5,6 is what the iLO wants. Adding a mapping table sounds like a good idea. How/where did you find the names above?

**Comment by pomac303** [comment]
Using ssh:
</>hpiLO-> show /map1/oemhp_dircfg1/

status=0
status_tag=COMMAND COMPLETED
Wed Mar  2 14:19:41 2016



/map1/oemhp_dircfg1
  Targets
    oemhp_keytab1
  Properties
    oemhp_dirauth=Directory Default Schema
    oemhp_localacct=Yes
    oemhp_dirsrvaddr=<your trusty ldap server>
    oemhp_ldapport=636
    oemhp_dirdn=N/A
    oemhp_usercntxt1=<your LDAP search path>
    oemhp_usercntxt2=
    oemhp_usercntxt3=
    oemhp_usercntxt4=
    oemhp_usercntxt5=
    oemhp_usercntxt6=
    oemhp_usercntxt7=
    oemhp_usercntxt8=
    oemhp_usercntxt9=
    oemhp_usercntxt10=
    oemhp_usercntxt11=
    oemhp_usercntxt12=
    oemhp_usercntxt13=
    oemhp_usercntxt14=
    oemhp_usercntxt15=
    oemhp_group1_name=Administrators
    oemhp_group2_name=Authenticated Users
    oemhp_group3_name=<your LDAP group path>
    oemhp_group4_name=
    oemhp_group5_name=
    oemhp_group6_name=
    oemhp_group1_priv=login,oemhp_rc,oemhp_vm,oemhp_power,config,admin
    oemhp_group2_priv=login,oemhp_rc,oemhp_vm,oemhp_power
    oemhp_group3_priv=login,oemhp_rc,oemhp_vm,oemhp_power,config,admin
    oemhp_group4_priv=0
    oemhp_group5_priv=0
    oemhp_group6_priv=0
    oemhp_dir_kerberos_enabled=Disabled
    oemhp_dir_kerberos_kdc_port=88
    oemhp_dir_kerberos_kdc_address=
    oemhp_dir_kerberos_realm=
  Verbs
    cd version exit show set delete


</>hpiLO-> 

This is on: iLO Firmware Version	1.87 Oct 27 2015

I've been trying to handle OA:s and connect to machines via the OA - which is a hell best avoided - so I've been using a few too many of these prompts by now... =)

**Comment by seveas** [comment]
Thanks! I'll add the mapping.

**Comment by seveas** [comment]
Fixed in 308259d
