### ISSUE TITLE
Unicode error... 

### ISSUE THREAD

**Issue by pomac303** [seveas/python-hpilo#103]
Hi again, it seems like the data we get back from HP isn't Unicode safe.... 

Perhaps making sure that the data is utf-8 ok by doing a .encode?

`entry['func']` is in this case get_host_data()
```
Traceback (most recent call last):
  File "./inventory.py", line 213, in <module>
    main()
  File "./inventory.py", line 209, in main
    checker.verify_ilo()
  File "./inventory.py", line 82, in verify_ilo
    self.info[entry['name']] = entry['func']()
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 1115, in get_host_data
    return self._info_tag('SERVER_INFO', 'GET_HOST_DATA', process=process)
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 700, in _info_tag
    header, message = self._request(root)
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 252, in _request
    message = self._parse_message(data[:pos])
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 558, in _parse_message
    message = etree.fromstring(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x90' in position 755: ordinal not in range(128)
```

**Comment by seveas** [comment]
Interesting. Could you share the raw XML? I've never gotten this and would like to create a testcase.

**Comment by pomac303** [comment]
Any good idea of how to dump it?

**Comment by seveas** [comment]
See http://seveas.github.io/python-hpilo/troubleshooting.html

**Comment by pomac303** [comment]
Nah, because thats also done in unicode ;)

Traceback (most recent call last):
  File "/usr/local/bin/hpilo_cli", line 321, in <module>
    main()
  File "/usr/local/bin/hpilo_cli", line 200, in main
    results = [getattr(ilo, method)(**params)]
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 1115, in get_host_data
    return self._info_tag('SERVER_INFO', 'GET_HOST_DATA', process=process)
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 700, in _info_tag
    header, message = self._request(root)
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 242, in _request
    header, data =  self._communicate(xml, self.protocol, progress=progress)
  File "/usr/local/lib/python2.7/dist-packages/hpilo.py", line 497, in _communicate
    fd.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x90' in position 1219: ordinal not in range(128)

**Comment by seveas** [comment]
That... surprises me. I thought we still had bytes here. Try `hpilo_cli -dd`, that should output the XML to the terminal.

**Comment by pomac303** [comment]
OK so it's the serial number - I did the following:
    def _parse_message(self, data_in, include_inform=False):
          data = data_in.encode('utf-8')
---
since it's where i hit the unicode issue... 

It now lists the serial number as " \u0090              "

Something has gone wrong on this machine at some time - which caused the error just making sure that the encoding you want is utf-8 somewhere early should fix this issue! =)

**Comment by seveas** [comment]
That's enough to give me something to reproduce in the parser, thanks!

**Comment by seveas** [comment]
Having poked at this a bit, I have to conclude that it's unfixable. Neither the HTTP header, nor the XML document contain any encoding information. So as a best-effort, we try to interpret whatever we get as latin-1, but realistically anything non-ascii may trigger errors and bugs.

**Comment by pomac303** [comment]
Ehm, I actually fixed it.

Ie the problem is in Python and we just have to keep Python happy, which is
doable

**Comment by seveas** [comment]
That may be a fix in your case, but it doesn't work in general. The iLO is supposed to escape all non-ascii characters in the xml output it generates, as that is the only way it can convey encoding of multi-byte characters. So I cannot accept that as a fix.

**Comment by pomac303** [comment]
While I agree that it feels kinda specific I'd say that:
1. it doesn't escape characters
2. Some of these strings can be user supplied or corrupted (which it is in
this case)

My personal opinion is that it shouldn't die from this but it would be nice
if it warned...

**Comment by seveas** [comment]
I think the best we can do is what's now in cc9a0dc, please test and let me know.

**Comment by pomac303** [comment]
My patch looked like this:
--- /usr/local/lib/python2.7/dist-packages/hpilo.py 2016-03-01
11:19:05.000000000 +0100
+++ hpilo.py 2016-03-03 15:14:46.405175235 +0100
@@ -544,7 +544,8 @@
         element = etree.SubElement(login, element, **attrs)
         return root, element

-    def _parse_message(self, data, include_inform=False):
+    def _parse_message(self, data_in, include_inform=False):
+        data = data_in.encode('utf-8')
         """Parse iLO responses into Element instances and remove
useless messages"""
         # Bug in some ilo versions causes malformed XML
         if '<RIBCL VERSION="2.22"/>' in data:
---

and for encode you can register error handlers or use 'replace' as a
error strategy, which i assume uses the U+FFFD, ‘REPLACEMENT
CHARACTER’ ie � - which should be ok.

It feels like your patch is doing work that is already handled nicely
by string.encode()
And i think it would be preferable to use that =)

**Comment by seveas** [comment]
Your patch is wrong. The data must be ascii-only, and we need to fix that as soon as we get data in, not when we feed it to the XML parser, so things like saving to files works too. The only way to do that is when decoding, and the only way to do that properly without breaking the chunked encoding is to replace non-ascii bytes with ascii characters. The questionmark seems most suitable.

**Comment by pomac303** [comment]
On Apr 26, 2016 18:41, "Dennis Kaarsemaker" <notifications@github.com>
wrote:
>
> Your patch is wrong. The data must be ascii-only, and we need to fix that
as soon as we get data in, not when we feed it to the XML parser, so things
like saving to files works too. The only way to do that is when decoding,
and the only way to do that properly without breaking the chunked encoding
is to replace non-ascii bytes with ascii characters. The questionmark seems
most suitable.

Yes, i know it's wrong, it did however solve my problem :)

What I'm saying is that the infrastructure for what you did already exists
in string.encode - no point in duplicating code ;)

**Comment by seveas** [comment]
I think you misread thea patch then, as I *am* using that infrastructure, though as part of decode, not encode :smiley:

**Comment by pomac303** [comment]
On Tue, 26 Apr 2016 at 19:43 Dennis Kaarsemaker <notifications@github.com>
wrote:

> I think you misread thea patch then, as I *am* using that infrastructure,
> though as part of decode, not encode [image: :smiley:]
>
> Yes, you're right - I just didn't get that you replaced all occurrences in
one go instead of having the error handler run per character - =)

In my defense, I looked really quickly ;)
