### ISSUE TITLE
Mapping table for set_host_power_saver

### ISSUE THREAD

**Issue by pomac303** [seveas/python-hpilo#104]
Hi,

get_host_power_saver_status returns a string, while the interface to set a value has to be a Integer, so here is a mapping table:

1 => OFF
2 => MIN
3 => AUTO
4 => MAX

or like i did in my code:
              mapping_table = {
                      'OFF': 1,
                      'MIN': 2,
                      'AUTO': 3,
                      'MAX': 4
              }

**Comment by seveas** [comment]
Sensible, will make the setter accept strings and map them.

**Comment by seveas** [comment]
Fixed in 6016df68
