### ISSUE TITLE
After upgrade the server 2.40 firmware hpilo_cli is not working

### ISSUE THREAD

**Issue by gvelu** [seveas/python-hpilo#109]
@seveas, After upgrade firmware to 2.40 i am getting below error.

    return ssl.wrap_socket(sock, ssl_version=self.ssl_version)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 54] Connection reset by peer

**Comment by seveas** [comment]
Unfortunately that looks like a broken iLO, not much python-hpilo can do about that. Here's what I would do:

- Try to reset the ilo using hponcfg and the iLO kernel driver (run this locally on the server: hpilo_cli localhost reset_rib) 
- If that doesn't work: Power down the server. Remove power cables if it's a discrete server, remove the blade from the chassis if it's a blade. Then power it back up
- If it still doesn't come back, contact HP support.

**Comment by gvelu** [comment]
Thanks @seveas . Server is good after the upgrade, also I am seeing the same issue on all upgraded servers, >2.40 servers good python-ilo works good.
