### ISSUE TITLE
Not able to get hpilo working

### ISSUE THREAD

**Issue by VijayaRaghavan81** [seveas/python-hpilo#114]
Hi There,

Many Thanks for providing such very useful tool.

Am very new to python and followed the instructions to installed both python and pytho-philo.

Is there any document/guide on how to start working on this tool.

I tried using python command line but I get the below error, not sure where is issue.

Error: 
NameError: name 'hpilo' is not defined

Any help much appreciated.

Thanks

**Comment by seveas** [comment]
Issues are not for support requests.
