### ISSUE TITLE
Does this work for HP Insight CMU (Moonshot)?

### ISSUE THREAD

**Issue by iamthemuffinman** [seveas/python-hpilo#117]
I suspect that it wouldn't, but I figured I'd ask anyway.

**Comment by seveas** [comment]
No idea what moonshot is, but if it's not an ilo, this doesn't work with it :)

**Comment by iamthemuffinman** [comment]
HP Moonshot does have an iLO, but this package doesn't work with it. No matter, I ended up switching my project to use Go for other reasons I won't go into here.
