### ISSUE TITLE
missing keyword in mod_network_settings

### ISSUE THREAD

**Issue by ralfutermann** [seveas/python-hpilo#125]
When trying to set dhcpv6_domain_name, I get an error:
TypeError: mod_network_settings() got an unexpected keyword argument 'dhcpv6_domain_name'

Adding dhcpv6_domain_name=None to 
mod_network_settings in hpilo.py fixes this.

regards, Ralf

**Comment by seveas** [comment]
Thanks, this has been added and will be released soon.
