### ISSUE TITLE
IloError Exception Error

### ISSUE THREAD

**Issue by abrahamrhoffman** [seveas/python-hpilo#126]
When calling 'update_rib_firmware', if the firmware is older than v1.30 (e.x. v1.20 or v1.21), I receive this stacktrace when attempting to upgrade:

Traceback (most recent call last):
  File "hp-ilo.py", line 74, in ?
    main()
  File "hp-ilo.py", line 53, in main
    upgrade_firmware(options.upgrade, options.username, options.password, datapath, options.version)
  File "hp-ilo.py", line 21, in upgrade_firmware
    ilo.update_rib_firmware(filename=afile)
  File "/usr/lib/python2.4/site-packages/hpilo.py", line 1887, in update_rib_firmware
    self._upload_file(filename, progress)
  File "/usr/lib/python2.4/site-packages/hpilo.py", line 355, in _upload_file
    raise IloError(body)
TypeError: exceptions must be classes, instances, or strings (deprecated), not IloError

Of course, I looked at the IloError class and it seems to be intact. Any suggestions on how to expose the underlying error without making changes to the class "IloError" ?

**Comment by seveas** [comment]
Assuming this is an iLO3, the firmware upgrade issue is well-known and [documented](http://seveas.github.io/python-hpilo/troubleshooting.html#failure-to-update-ilo3-firmware)

As for the strange IloError, I don't know and no longer have any systems with python 2.4 to test.

**Comment by seveas** [comment]
Ah, in python 2.4 exceptions cannot be new-style classes. That's a bit annoying.

**Comment by seveas** [comment]
Should be fixed in 904438f.
