### ISSUE TITLE
issue setting IPv6 address in python-hpilo

### ISSUE THREAD

**Issue by dietsja** [seveas/python-hpilo#128]
Hello:

I am having an issue updating the HP ILO's IPv6 Address. I can manually set the IPv6 via this:

ilo.mod_network_settings(ipv6_address = '2001:123:45:678:910:ff2::')

However, I cannot set it like this: 
j = 1 
ilo.mod_network_settings(ipv6_address = "'2001:123:45:678:910:ff2::" + hex(j)[2:] + "'")

I keep getting an invalid IP address and I feel like it's the quotes, but I cannot figure it out. Any help would be appreciated.

**Comment by jrosenboom** [comment]
Why do you add the additional quotes? Just leave them away, this should work fine:

lo.mod_network_settings(ipv6_address = "2001:123:45:678:910:ff2::" + hex(j)[2:])

**Comment by dietsja** [comment]
Thanks jrosen, knew it was simple.
