### ISSUE TITLE
handle error messages

### ISSUE THREAD

**Issue by coryschwartz** [seveas/python-hpilo#129]
If an errror getting info on the ilo, the xml schema not fully filled out. Instead, you get something like this:

```
<RIBCL VERSION="2.23">
<RESPONSE
    STATUS="0x007D"
    MESSAGE='XXXXXXXXXXXXX SOME ERROR MESSAGE'
     />
</RIBCL>
```

Under normal circumstances, an additional tag would be there at the same level as the RESPONSE tag which contains the requested information. When there is an error, the additional tag does not exist. python-hpilo attempts to look for the additional tag and when it doesn't find one, throws an exception.

expected behavior:
notice the response has an error message. Return the error message.

**Comment by seveas** [comment]
python-hpilo doesn't look at the additional tag, but interprets the error properly and raises an iloerror based on the code and message in the response. If you see it do otherwise, please provide full output.
