### ISSUE TITLE
'snmp_user_profile_1' keys

### ISSUE THREAD

**Issue by nivazri** [seveas/python-hpilo#133]
what are the keys for "snmp_user_profile_1":

https://pythonhosted.org/python-hpilo/snmp.html#hpilo.Ilo.mod_snmp_im_settings

security_name(username)
authentication_protocol (sha or md5)
authentication_passphrase
privacy_protocol (aes or des)
privacy_passphrase

**Comment by seveas** [comment]
Good catch. The documentation for that function could use a proper edit. Mind having a go at a patch? If not, I'll pick it up in a few days/weeks.

**Comment by nivazri** [comment]
the keys are:
ilouser -> security_name(username)

for AUTHN_PROTOCOL: 0 or 1
0 is for MD5,
1 is for SHA

for PRIVACY_PROTOCOL: 0 or 1
0 is for DES,
1 is for AES

AUTHN_PASSPHRASE
PRIVACY_PASSPHRASE
