### ISSUE TITLE
Onboard Admin using Lights Out 100

### ISSUE THREAD

**Issue by rdevans0** [seveas/python-hpilo#138]
I'm having some trouble getting hpilo.py to play nice with a very old on-board ILO interface. It works nicely with my head node, but the other nodes do not work. 

Head node (works)
ILO 2 (Firmware 1.78)

Sub node (does not work)
Lights Out 100 (Firmware 4.03)
Proliant SL2x170z G6

I have no problem accessing this node through ssh, but running hpilo with debug shows the following:
```
>>> ilo.get_fw_version()
Connecting to 10.42.xxx.yyy port 443
Connecting to 10.42.xxx.yyy port 443
Sending XML request, 132 bytes
POST /ribcl HTTP/1.1
Host: localhost
Content-Length: 52
Connection: Close


<?xml version="1.0"?>
<RIBCL VERSION="2.0"></RIBCL>
Received 0 bytes
...
hpilo.IloError: Remote returned bogus data, maybe it's not an iLO
```

**Comment by seveas** [comment]
"lights out 100" is not a real ilo and doesn't support the  xml api
