### ISSUE TITLE
Can we add SEND_SNMP_TEST_TRAP method as well? [eom]

### ISSUE THREAD

**Issue by fountain72** [seveas/python-hpilo#140]

**Comment by seveas** [comment]
That was added a while ago in ec1e678f

**Comment by fountain72** [comment]
Hello Dennis,

I downloaded the latest version and it shows not recognized method.

On Jul 8, 2017 1:14 PM, "Dennis Kaarsemaker" <notifications@github.com>
wrote:

Closed #140 <https://github.com/seveas/python-hpilo/issues/140>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/seveas/python-hpilo/issues/140#event-1155601959>, or mute
the thread
