### ISSUE TITLE
authentication_failure_logging mapping

### ISSUE THREAD

**Issue by tbouman** [seveas/python-hpilo#143]
It looks like authentication_failure_logging maps to the wrong value when trying to set it using hpilo_cli.
When setting the authentication_failure_logging in the global settings, the setting authentication_failure_settings=0 maps in the XML to:
```
<AUTHENTICATION_FAILURE_LOGGING
 VALUE="NO"
>
```
authentication_failure_settings=1 maps in the XML to:
```
<AUTHENTICATION_FAILURE_LOGGING
 VALUE="YES"
>
```
These both result in an Invalid Integer error response from the ILO.

Other values are working as intended.

Documentation:
AUTHENTICATION_FAILURE_LOGGING—Specifies logging criteria for failed authentications.
Possible values include:
• 0—Disabled
• 1—Enabled (records every authentication failure)
• 2—Enabled (records every second authentication failure)
• 3—Enabled (records every third authentication failure: this is the default value.)
• 5—Enabled (records every fifth authentication failure)

**Comment by seveas** [comment]
Thanks, fixed in b39e04b
