### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by erpadmin** [seveas/python-hpilo#147]
connecting to older iLO 3 and getting Cannot establish ssl session with xyz SSLV3_ALERT_HANDSHAKE_FAILURE

Any way that I can get around this?

**Comment by ewwhite** [comment]
You need to upgrade your ILO3 to at least version 1.28
See: https://serverfault.com/a/613151/13325

--
Edmund White

**Comment by erpadmin** [comment]
alright thanks for the information
