### ISSUE TITLE
Missing argument in mod_network_settings

### ISSUE THREAD

**Issue by hansdg1** [seveas/python-hpilo#149]
I noticed that `get_network_settings()` is returning an attribute that `mod_network_settings` does not support.  

The attribute is `nic_fail_over_delay` and has a default value of 300. It looks like it must've been added recently.

This is occurring on iLO4's firmware 2.54. 

I found references to it in the [December 2016 HPE iLO 4 Scripting and Command Line Guide](http://h20565.www2.hpe.com/hpsc/doc/public/display?docId=c03334058).

**Comment by seveas** [comment]
Thanks, fixed in 0d5d870
