### ISSUE TITLE
ILO 2.55 update may segfault hpasmlited 

### ISSUE THREAD

**Issue by ewwhite** [seveas/python-hpilo#153]
FYI 

Routine update of ILO4 on some Gen8 ProLiant DL360p and DL380p units resulted in the crashing of hpasmlited process and losing ILO control of the fans/temperature sensors.

This weekend, 4 of 300 Gen8 systems under my management were reported to have fans running at full speed and no sensor/fan/power stats.

`dmesg` output below:

```
hpilo 0000:01:00.2: Open could not dequeue a packet
hpilo 0000:01:00.2: Open could not dequeue a packet
hpilo 0000:01:00.2: Open could not dequeue a packet
hpilo 0000:01:00.2: Open could not dequeue a packet
hpasmlited[17904]: segfault at 8 ip 0000000000425409 sp 00007ffc8ff864c0 error 4 in hpasmlited[400000+38000]
hpasmlited[35511]: segfault at 8 ip 0000000000425409 sp 00007ffeb8faad40 error 4 in hpasmlited[400000+38000]
```

This seems to be isolated to the earliest system boards of Gen8 systems; possibly 2012/2013-era servers. A regular reboot resolved this.

![img_3511](https://user-images.githubusercontent.com/5448374/30809890-f2b76d58-a1c8-11e7-9f76-8967b57329a7.jpg)

**Comment by seveas** [comment]
Hi Ed,

Thanks for reporting this, but I don't think there's much python-hpilo can do about this. I'll close this issue as discussed on slack.
