### ISSUE TITLE
Please push release to PyPi

### ISSUE THREAD

**Issue by cueball23** [seveas/python-hpilo#154]
Could you push the current 4.0 release to PyPi?

Many thanks :)

**Comment by seveas** [comment]
I tried, but the new pypi ignores my uploads. They get accepted but nothing happens. Clues on how to fix this would be most appreciated.

**Comment by cueball23** [comment]
I suspect the "packages" Keyword is missing in setup.py.

packages=['python-hpilo']

https://github.com/pypa/sampleproject/blob/master/setup.py

**Comment by seveas** [comment]
No, that's for when you ship packages, python-hpilo is only a single module.

**Comment by cueball23** [comment]
According to the python-packaging minimal setup:
- license
- packages
- zip_safe
are missing, I don't know if this is in any way related to the update problem. 

> setup(name='funniest',
      version='0.1',
      description='The funniest joke in the world',
      url='http://github.com/storborg/funniest',
      author='Flying Circus',
      author_email='flyingcircus@example.com',
      license='MIT',
      packages=['funniest'],
      zip_safe=False)
from http://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by cueball23** [comment]
Are you using "python setup.py upload" or the new "twine" utility?
The new "twine" utility replaced the direct usage of "python setup.py upload". Both should work but you never know. ;)

**Comment by seveas** [comment]
4.1 is now on pypi
