### ISSUE TITLE
LDAP Directory Authentication - Use Directory Default Schema

### ISSUE THREAD

**Issue by transce** [seveas/python-hpilo#157]
Apologize if this has been brought up before and there is a workaround.

Under Security->Directory->Authentication Options, there is LDAP Directory Authentication.
There are three choices:
Disabled
Use Extended Schema
Use Directory Default Schema

It appears that mod_dir_config(dir_authentication_enabled=True) sets it to Use Extended Schema. Is there any way to specify Use Directory Default Schema instead?

Current hardware info:
DL360 G9
Firmware 2.53

**Comment by transce** [comment]
I'm still looking for a solution to this. I am currently using pexpect to ssh into the iLO and configure it that route. I would much rather have hpilo do the work for me as pexpect doesn't work 100% of the time. It misses the carriage return on the command.

**Comment by seveas** [comment]
This can be done with `mod_dir_config(dir_enable_grp_acct=True)`
