### ISSUE TITLE
User Account Login Permission

### ISSUE THREAD

**Issue by Skitond** [seveas/python-hpilo#180]
Hello

In the functions for user editing (**get_user, add_user, mod_user**), there are a couple of values that can be set. However none of these are for granting an account only the login right, which you can set through the GUI on ILO5 devices.
The values you can set with this module are: **USER_NAME, USER_LOGIN, ADMIN_PRIV, REMOTE_CONS_PRIV, RESET_SERVER_PRIV, VIRTUAL_MEDIA_PRIV** and **CONFIG_ILO_PRIV**

Essentially what I want to do is automate the creation of an account for only gathering information from the **get_embedded_health** function and not have permissions for doing anything else. For this to be done an account seems to need the Login permission set through the GUI.

Any insight as to how this could be accomplished would be welcome!

**Comment by seveas** [comment]
Setting all the `*_priv` argument to False should do the trick.

**Comment by Skitond** [comment]
Now it works. That did the trick!

Thanks for all your hard work! :)
