### ISSUE TITLE
Include cryptographic checksum in firmware.conf

### ISSUE THREAD

**Issue by ypid-geberit** [seveas/python-hpilo#182]
This would be useful to ensure that the correct file was downloaded. Also, in cases proxies are used or the files are self hosted as mentioned in the docs, something could go wrong or an attach is performed.

The question would be from which file the checksum should be stored. I would propose the original scexe file because that allows to check the checksum (which is distributed separatly, by this repo) before parsing an potentially untrusted file.

Reason and Examples:

* https://github.com/hamishcoleman/thinkpad-ec/blob/master/Descriptions.txt
* https://github.com/rootkovska/codehash.db

Effects:

* https://github.com/seveas/python-hpilo/blob/master/firmware.conf
* https://github.com/seveas/python-hpilo/blob/master/hpilo_fw.py

**Comment by seveas** [comment]
This doesn't help against attacks. What would prevent the attacker who can change the .scexe files in flight from also changing firmware.conf?

And it has *very* limited value against accidents: the firmware is already signed and the iLO won't accept anything that's corrupt.

So I'll need to be convinced a lot more before accepting this idea :smile:

**Comment by ypid-geberit** [comment]
Good that I still have a few arguments queued up then :)

That is a valid point which outside of the scope of this issue but also needs to be handled. There is one answer with a few implementations. Digital signatures. Linux distros do this quite well for many years now. PIP allows to upload signatures but not to check them. Git has good support for it. In your case, as you download the file on runtime, you would need to check the signature each time. GnuPG and OpenSSL come to mind.

> the firmware is already signed and the iLO won't accept anything that's corrupt.

Do you have details on that signature or is it just a checksum you can calculate yourself? Or perhaps some home-brown crypto which will break if you look at it (example [mec-tools](https://github.com/eigenmatt/mec-tools))?

The thread model I had in mind was https://downloads.hpe.com gets compromised. There is a reason software deployment uses locally verified signatures or if the origin is not able to provide signatures, use locally verified checksums.

**Comment by seveas** [comment]
The only new argument I see in that reply is 'what if the firmware verification is weak?'. I don't know the details of the firmware verification, but am not aware of any tools to break it or any published weaknesses, so that argument is pretty weak as well.

Linux distro signatures are bootstrapped by embedding trusted keys on the install iso. So when you trust the iso, you trust the updates. For firmware.conf, that bootstraping is a lot more difficult, and due to the firmware verification on the iso itself not quite worth it.

downloads.hpe.com getting compromised is about as likely as github.com getting compromised, so checksums in firmware.conf also don't really add anything there.

So I hope you have more arguments :)

**Comment by ypid-geberit** [comment]
> For firmware.conf, that bootstraping is a lot more difficult, and due to the firmware verification on the iso itself not quite worth it.

Not necessarily. Your Python module is in Debian (https://packages.debian.org/search?keywords=hpilo). When you now harden the down-streaming path to for example Debian by implementing #184 you are pretty far with mitigating the bootstrapping problem.

> but am not aware of any tools to break it or any published weaknesses, so that argument is pretty weak as well.

Having dealt with a few firmware formats and looking into reversing and patching one of them ([thinkpad-ec](https://github.com/hamishcoleman/thinkpad-ec/)) I have my doubts for every security feature which can not be reviewed (free access to the source code and build chain) so I would still recommend to do this additionally in python-hpilo. Also, we have no idea how good HPE is with keeping their private keys private. Their website setup does not look too well done at some parts. There is a reason why https://github.com/rootkovska/codehash.db exists. Lets bump our thread model up once more: Targeted attacks.

At least the HPE docs have some details on this:

> Authorized firmware updates – iLO firmware images are digitally signed with a 2048-bit
 private key. The boot block checks the digital signature every time iLO comes out of reset.
iLO checks the digital signature before allowing a firmware update to proceed. Remote
flashing requires login authentication and authorization, including optional two-factor
authentication.
> 
> Image Validation
> The entire image is hashed with SHA256 and signed using Hewlett Packard Enterprise’s RSA
2048-bit private key. This signature block is pre-pended to the firmware binary image.
> 
> Boot-Time Integrity Check
> At boot time, each piece has its signature validated before it is allowed to execute. Subsequent
pieces are checked by the previous ones until iLO is fully booted.

Source: https://support.hpe.com/hpsc/doc/public/display?docId=c04530504

Sounds reasonable, at least when they keep increasing their RSA key size. 2048 bit is not really state of the art anymore.

**Comment by seveas** [comment]
#184 doesn't help Debian unless they actually check the signature, and nothing tells me they do. It's also only one of the distribution channels, and unfortunately people will just add any old gpg key to the apt or yum/dnf keyring that they find these days.

I'm afraid that the scaremongering about targeted attacks also doesn't work for me. Feel free to maintain a list of firmware hashes yourself, but I still don't think that the added work adds enough value to make it worth it.

**Comment by ypid-geberit** [comment]
@seveas When we are now talking about the extra work, one could just automate that. I addressed your other points in #184.

**Comment by ypid-geberit** [comment]
You might be interested: https://airbus-seclab.github.io/ilo/SSTIC2018-Slides-EN-Backdooring_your_server_through_its_BMC_the_HPE_iLO4_case-perigaud-gazet-czarny.pdf

**Comment by seveas** [comment]
Yeah, that's quite the SNAFU there :smile:
