### ISSUE TITLE
RPM repository is down

### ISSUE THREAD

**Issue by ewwhite** [seveas/python-hpilo#185]
Hello,

The RPM repositories and build at the following address are down:
http://download.opensuse.org/repositories/home:/seveas:/python/RHEL_6/noarch/ 

Is there any plan to reenable this?

**Comment by ewwhite** [comment]
I don't believe `yum-plugin-copr` is available in EL6 releases.

This impacts a large user base of EL6 systems - EL7 is only beginning to be approved for rollout at my larger enterprise customers. I'll see what I can do here, but needed to understand the plan.

**Comment by seveas** [comment]
You don't *have* to use the copr plugin, that just makes adding the .repo file and gpg key easier. You can just add it as a normal repo and import the gpg key. I'll add some instructions to the install docs about that.

**Comment by seveas** [comment]
Done.
