### ISSUE TITLE
mod_encrypt_settings - global name 'val' is not defined error

### ISSUE THREAD

**Issue by daugavpils** [seveas/python-hpilo#194]
Hi,

 I am trying to change encryption settings as below but getting some unclear message
`
ilo.mod_encrypt_settings(eskm_user_login,eskm_user_password,eskm_grp_name,eskm_cert_name,enable_redundancy,eskm_primary_server_address,eskm_primary_server_port,eskm_secondary_server_address,eskm_secondary_server_port)  

Traceback (most recent call last):  

  File "<stdin>", line 1, in <module>  
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 1397, in mod_encrypt_settings  
    if vars[val] is not None:   
NameError: global name 'val' is not defined  
`

**Comment by daugavpils** [comment]
if I am not mistaken, the issue is on line 1423 below
`        for var in vars:
            if vars[val] is not None:
                elements.append(etree.Element('ESKM_' + var.upper(), VALUE=vars[var]))
        return self._control_tag('RIB_INFO', 'MOD_ENCRYPT_SETTINGS', elements=elements)`

**Comment by seveas** [comment]
Thanks for reporting and pointing to the line with the error 😄 

Foxed in 6e71e01
