### ISSUE TITLE
Add support for ilo5 versions

### ISSUE THREAD

**Issue by naorc123** [seveas/python-hpilo#224]
Hey,
There is the file firmware.conf, we pull our ILO versions from it.
according to [HP release](https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX_84db76fd306e43e4810c5fca63#tab-history) there are newer versions.
Can you update the repository so maintain also newer ilo5 versions?

**Comment by ewwhite** [comment]
I'm just noticing this as well. Any updates?

**Comment by ypid-geberit** [comment]
From me as an outsider, it looks like PR are handled normally (ref: #228) so if you need this, maybe just do the work instead of waiting/pressuring others to do it for you?

**Comment by seveas** [comment]
Newer versions have been added to firmware.conf
