### ISSUE TITLE
Add Focal Fossa dist to your launchpad PPA

### ISSUE THREAD

**Issue by mahmoudshirivaramini** [seveas/python-hpilo#230]
My OS is Ubuntu 20.04 LTS Focal Fossa and tried to install `python-hpilo` according to [documentation](http://seveas.github.io/python-hpilo/install.html).
But  Focal Fossa distribution does not present on you [launchpad PPA](http://ppa.launchpad.net/dennis/python/ubuntu/dists/). So I request this as a feature.

**Comment by seveas** [comment]
I'm actually going to remove my ppa entirely, so future versions will not be shipped as debian packages.
