### ISSUE TITLE
iLO5 update fails due to required version

### ISSUE THREAD

**Issue by chris240189** [seveas/python-hpilo#240]
I have an iLO5 running 1.39 (flashed via python-hpilo).
Upon updating to 2.18 (with the last update of python-hpilo) the script fails with `hpilo.IloError: Firmware flash failed.`.

Flashing the bin file directly via the webgui fails too with "the file siganture is invalid".
The reason could be that iLO5 1.40 is required for updating further (source https://community.hpe.com/t5/proliant-servers-ml-dl-sl/ilo5-firware-update-fails-quot-the-file-siganture-is-invalid/td-p/7085862)

updating to iLO5 1.40 manually and then using the python-hpilo updates as expected flawlessly to 2.18

**Comment by seveas** [comment]
Unfortunately there's not much python-hpilo can do. This is actually a [known issue](https://seveas.github.io/python-hpilo/troubleshooting.html#failure-to-update-ilo3-firmware) thogh the documentation only talks about iLO3. I'll update it to mention iLO5 and the 1.40 step.
