### ISSUE TITLE
RC4-SHA is no longer available in openssl

### ISSUE THREAD

**Issue by basilhendroff** [seveas/python-hpilo#241]
Hello!

Similar to https://github.com/seveas/python-hpilo/issues/232, but on iLO4.

For full details, please refer to the Let's Encrypt community thread https://community.letsencrypt.org/t/hp-ilo4-ssl-circular-reference/137076

I'm seeing the issue on the embedded iLO4 on a HP Gen8 Microserver

```
# hpilo_cli -v
4.4.1
# pip --version
pip 20.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by basilhendroff** [comment]
There is a solution to this issue. Please refer to abovementioned thread for the details. Does it warrant a change to hpilo.py?

**Comment by seveas** [comment]
I see several issues in that thread. There's an issue about rc4 and this transfer-encoding issue. I did see a solution for the rc4 issue, but not for the transfer-encoding issue. What did I miss?

**Comment by basilhendroff** [comment]
Btw, you rate a mention on the FreeNAS community resource [Let's Encrypt Local Servers and Devices](https://www.truenas.com/community/resources/lets-encrypt-local-servers-and-devices.162/). Please let me know if you manage to resolve this issue and I'll remove the tweak I made to the [install script](https://github.com/basilhendroff/truenas-iocage-letsencrypt/blob/main/le-jail.sh) for the resource around line 145.

**Comment by seveas** [comment]
This is fixed now.
