### ISSUE TITLE
HP DL360 ilo3 gen7 - fw upgrade using ipmi

### ISSUE THREAD

**Issue by shaikk-arch** [seveas/python-hpilo#245]
Hi leo-minorui ,

How are you ?

Could you able to tell me if there is a way i can update ILO Firmware using IPMI tool  for ILO3 DL360 Gen7 ? i was looking into all doc but no luck ? please help me with the command it would be helpful
I have all ILO3 Gen7 = 1.87 version which needs a upgrade

IPMI or other way to upgrade on ILO3 DL360 Gen7, i tried using "hpilo and RestAPI" on ubuntu it didn't work.
OR 

Can you please suggest me a way to upgrade ILO3 DL360 Gen7 using any utility or other way?

Thanks!

**Comment by seveas** [comment]
python-hpilo does not work via ipmi. It either works via the ilo's network connection or using hponcfg and the ilo driver.
