### ISSUE TITLE
Outdated COMPAQ (HP) iLO v2 sslv3 (tls1/aes-128) issue

### ISSUE THREAD

**Issue by sxiii** [seveas/python-hpilo#266]
I've got an old server that I'm trying to connect.

I know this cyphersuite isn't supported anymore; but to update it I need find a way to connect.

I've tried a lot of browsers and finally, Firefox 15.0.1 allowed me to accept the warning and get into log-in. Now, even though I got access to log-in, the password isn't working from the sticker. So I decided to try python-hpilo but it does not allow me:

```
hpilo.IloCommunicationError: Cannot establish ssl session with 192.168.0.100:443: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)
```

So this should be related to same AES-128 cyphersuite being unsupported; but still. Tried python2 and python3. Is there a ways around it? Maybe some --skip-ssl flag etc.

Thanks

**Comment by seveas** [comment]
You'll need to use an older python version which still supports older ssl versions.
