### ISSUE TITLE
update_firmware support

### ISSUE THREAD

**Issue by seveas** [seveas/python-hpilo#54]
Apparently there's an UPDATE_FIRMWARE (note: not UPDATE_RIB_FIRMWARE) tag that can be used to update device firmware. If this is non-intrusive, add support for it and somehow update the mirroring scripts/firmware.conf generator to use it.

**Comment by abrahamrhoffman** [comment]
Hi Seveas,

I just got a chance to try your fix on Python 2.4. Unfortunately, I am now unable to import hpilo:

Python 2.4.3 (#1, Oct 23 2012, 22:02:41)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hpilo
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "/usr/lib/python2.4/site-packages/hpilo.py", line 147, in ?
    class IloError(Exception):
  File "/usr/lib/python2.4/site-packages/hpilo.py", line 142, in __new__
    klass = super(IloErrorMeta, cls).__new__(cls, name, parents, attrs)
TypeError: Error when calling the metaclass bases
    a new-style class can't have only classic bases
