### ISSUE TITLE
get ilo license on g5 proliant

### ISSUE THREAD

**Issue by kellerkind** [seveas/python-hpilo#65]
Getting/Setting iLO License on Proliant G5 with firmware version 2.15   01/17/2013 failed.

> >>> ilo.get_all_licenses()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "hpilo.py", line 1087, in get_all_licenses
>     return self._info_tag('RIB_INFO', 'GET_ALL_LICENSES', process=process)
>   File "hpilo.py", line 642, in _info_tag
>     header, message = self._request(root)
>   File "hpilo.py", line 216, in _request
>     message = self._parse_message(data)
>   File "hpilo.py", line 530, in _parse_message
>     raise IloError(message, status)
> hpilo.IloError: Syntax error: Line #0: syntax error near "" in the line: "". You may have tried to use a feature this iLO version or firmware version does not support.

**Comment by seveas** [comment]
`get_all_licenses` only works on iLO3 and iLO4.

**Comment by seveas** [comment]
You may want `get_fw_version` instead:
```
>>> pprint(my_ilo.get_fw_version())
{'firmware_date': 'Aug 26 2011',
 'firmware_version': '1.26',
 'license_type': 'iLO 3 Advanced',
 'management_processor': 'iLO3'}
```
