### ISSUE TITLE
Make firmware.conf location configurable

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#67]
For running on servers without direct internet acces, it would be nice if the URL of firmware.conf was overridable in .ilo.conf. This would allow placing it and the latest firmware versions on a local mirror in a dmz and keep the internal servers up to date.

**Comment by seveas** [comment]
As with #68, this has been a wishlist item for me for a while.

**Comment by seveas** [comment]
Implemented in 985610f
