### ISSUE TITLE
Local mirror support for firmware download

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#68]
Hi,

a option for .ilo.conf would be great that allows to specify a custom firmware download location mirror prefix. This would mean that one could execute on the local mirror (with access to the internet):

    $ cat /etc/cron.daily/update-ilo-firmware 
    #!/bin/sh
    cd /srv/mirror/ilo-firmware
    /usr/bin/hpilo_cli download_rib_firmware all | grep -v "was already downloaded"

And on the internal server that has no internet access:

    $ cat ~/.ilo.conf
    [firmware]
    mirror-prefix = http://my-local-mirror.internal/hp-firmware/

and then

    $ hpilo_cli update_rib_firmware version=1.82
    # downloads and installs firmware from http://my-local-mirror.internal/hp-firmware/ilo3_182.bin

**Comment by seveas** [comment]
Agreed.  This has been a wishlist thing for me for a while now.
Op 3 mrt. 2015 19:02 schreef "Karsten Heymann" <notifications@github.com>:

**Comment by seveas** [comment]
Implemented in 985610f
