### ISSUE TITLE
missing output from get_host_data

### ISSUE THREAD

**Issue by kellerkind** [seveas/python-hpilo#69]
Using ./locfg and get_host_data example:

    <RIBCL version="2.21">
    <LOGIN USER_LOGIN="adminname" PASSWORD="password">
    <SERVER_INFO MODE="READ" >
    <GET_HOST_DATA />
    </SERVER_INFO>
    </LOGIN>
    </RIBCL>

this will return following data wrapped by the SMBIOS_RECORD node:

	<GET_HOST_DATA>
	 <SMBIOS_RECORD TYPE="0" B64_DATA="ABgAAAECAPADf4DayX0AAAAAAwf//wEySFAAUDY3ADA1LzA1LzIwMTEAAA==">
	  <FIELD NAME="Family" VALUE="P67"/>
	  <FIELD NAME="Date" VALUE="05/05/2011"/>
	 </SMBIOS_RECORD>

The output with hp_cli results the inner data of SMBIOS_RECORD. The node itself is missing:

    hpilo_cli 10.231.12.12 get_host_data -l user -p password

	>>> pprint(my_ilo.get_host_data())
	[{'Date': '05/05/2011',
	  'Family': 'P67',
	  'b64_data': 'ABgAAAECAPADf4DayX0AAAAAAwf//wEUSFAAUDY3ADA1LzA1LzIwMTEAAA==',
	  'type': 0},
	 {'Product Name': 'ProLiant DL380 G7',
	  'Serial Number': 'CZ213300D2      ',
	  'UUID': '583914CZ213300D2',
	  'b64_data': 'ARsAAQQFAAE1ODM5MTRDWjIxMzMwMEQyBgIDQ1oyMTMzMDBEMiAgICAgIAA1ODM5MTQtQjIxICAgICAgAFByb0xpYW50AEhQAFByb0xpYW50IERMMzgwIEc3ACAgICAgICAgICAgICAgICAAAA==',
	  'cUUID': '39333835-3431-5A43-3231-333330304432',
	  'type': 1},

**Comment by seveas** [comment]
I'm not sure I understand your bugreport. As far as I can see, the returned dict contains all attributes of both the smbios_record node (b64_data and type) and the field tags (Family and Date). Am I overlooking something?

**Comment by kellerkind** [comment]
OK, I've overlooked that you have attribute "type" included in json output. I was only missing the outer smbios_record.
