### ISSUE TITLE
call_delayed should return the incoming data as a list

### ISSUE THREAD

**Issue by kellerkind** [seveas/python-hpilo#70]
call_delayed() 

returns a list of dicts for 

    get_host_data(). 

For 

    get_fw_version()

it only returns a single dict. It should return a merged list of entries instead.

**Comment by seveas** [comment]
It's not `call_delayed` that returns the list of dicts, that's `get_host_data` itself. Similarly, `get_fw_version` returns a single dict, whether it's run  as part of a delayed call or not. `call_delayed` does not (and should not) change the return type of any of the called function. If it does, that is a bug.

Here's an example from the command line, the `+` makes it use `call_delayed`.:
```
$ hpilo_cli 10.1.2.3 get_fw_version
>>> pprint(my_ilo.get_fw_version())
{'firmware_date': 'Aug 26 2011',
 'firmware_version': '1.26',
 'license_type': 'iLO 3 Advanced',
 'management_processor': 'iLO3'}

$ ./hpilo_cli 10.1.2.3 get_fw_version + get_uid_status
>>> pprint(my_ilo.get_fw_version())
{'firmware_date': 'Aug 26 2011',
 'firmware_version': '1.26',
 'license_type': 'iLO 3 Advanced',
 'management_processor': 'iLO3'}
>>> print(my_ilo.get_uid_status())
OFF
```

**Comment by kellerkind** [comment]
I understand that this are the functions that are called. I have the problem when parsing the resulting data from ```call_delayed``` because it is a mix of dicts or list. Currently I have a function to merge the results in one big list but it would be a benefit to relay on a consistent data stream from ```call_delayed```.

	def get_data_as_list(data):
	  d = []
	  for row in data:
		if isinstance(row, list):
		  d += row
		else:
		  d.append(row)

	  return d

**Comment by seveas** [comment]
That makes no sense to me at all. The returned items are all different, because they are returned by different functions. Treating them as one block of data is definitely not the way to approach this.
