### ISSUE TITLE
Wishlist: Add support for HP Onboard Administrators

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#71]
Being able to access the HP Onboard Administrator to at least read the settings from HP Bladecenters could come handy in many situations. I'm not aware of any official documentation regarding the HTTP Interface but they support at least a /xmldata?-URL, for example http://hpoba1.mydomain/xmldata?item=all. If I understand http://h30499.www3.hp.com/t5/HP-BladeSystem-Management/Onboard-Administrator-OA-XML-documentation/td-p/2323763#.VPmkaHVUXmE correctly, this interface is read-only.

**Comment by seveas** [comment]
There's no http/xml/rest API for the OA's like there is for the iLO's, the xmldata call is all they have. And python-hpilo should already support this.

**Comment by seveas** [comment]
Just checked and `xmldata()` works, but there are some empty dicts in the output so it needs fixing. Is there anything in particular that you want from the /xmldata url that's not in the xmldata() result?

**Comment by kasimon** [comment]
You are right, I should have tried this myself before posting. I'll have a look at the resulting xml data and see what's missing. Btw, hpilo_cli should not require credentials for the xmldata command, should I file a separate bug report for this?

**Comment by seveas** [comment]
I realized the same when I was testing this, and am already fixing it, so no need to file a new bug report :)

**Comment by seveas** [comment]
Credentials issue now fixed in 744e2b0, will poke at xmldata later when I have more time.

**Comment by seveas** [comment]
Fixed in db544a4
