### ISSUE TITLE
Feature suggestion: initial ilo login barcode scanning support

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#72]
Photos of the barcode labels containing the inital iLO login data can be easily parsed with the zbar library:

```
$ zbarimg 20150129_110526.jpg 
CODE-128:INITIALPASS
CODE-128:ILOCZABCDEXYZ
CODE-128:CZABCDEXYZ
scanned 3 barcode symbols from 1 images in 3.9 seconds
```

This can nicely be used from python with the python-zbar module. Maybe there is place in pyhton-hpilo for some kind of contrib "credential collection" script. I have some rough example code working that could become such a script if of any interest.

**Comment by seveas** [comment]
There's definitely room for that. I'm working on a rework of the docs and incorporating mores such examples. hpilo_ca will be "demoted" to example for instance, and I'm adding something we use here that stores ilo data in elasticsearch and some scripts that use that data to find ilos with obsolete firmware and upgrade them.
