### ISSUE TITLE
mod_snmp_im_settings: trapcommunity syntax unclear

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#73]
ilo.mod_snmp_im_settings(snmp_address_1_trapcommunity='public')

results in

    Traceback (most recent call last):
      File "./ilosetup.py", line 137, in <module>
        serverfqdn="", ilo_advanced_key=args.ilokey, deleteuser="")
      File "./ilosetup.py", line 100, in setup_server
        snmp_address_1_trapcommunity='public',
      File "/usr/lib/python2.7/dist-packages/hpilo.py", line 1402, in mod_snmp_im_settings
        for key_ in val.keys():
    AttributeError: 'str' object has no attribute 'keys'

Looking at hpilo.py, there seems to be some kind of special handling for these fields, but the expected syntax is unclear and get_snmp_im_settings gives only a plain string for this field if set directly in the ilo.

**Comment by seveas** [comment]
that call expects a dict `{'name': community_name, 'version': snmp_version}`, e.g. `{'name': 'public', 'version': 'v2c'}`. This should be made much clearer in the docs.

**Comment by kasimon** [comment]
I tried it, it's not `'name'` but `'value`': `'value': 'public', 'version': "2c"}`. Then it works.

**Comment by seveas** [comment]
Fixed in the documentation rework.
