### ISSUE TITLE
hpilo_ca syntax error

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#75]
Hi,

while trying to update the certificate of a ilo 1 system (which is not supported, as I learned since then), the following error occurred:

    $ hpilo_ca sign <ilo1> -l <root> -p <redacted>
    (1/5) Checking certificate config of 172.16.21.11
    Traceback (most recent call last):
      File "/usr/bin/hpilo_ca", line 259, in <module>
        main()
      File "/usr/bin/hpilo_ca", line 138, in main
        elif re.match(r'^iLO{3-9}$', fw_version['management_processor']):
    NameError: global name 're' is not defined

This is the only occurrence of 're' in the whole script, so I doubt this condition ever worked in its current form.

**Comment by seveas** [comment]
Looks like I never hit that particular issue myself. Thanks for reporting!

**Comment by seveas** [comment]
Fixed in the documentation rework.
