### ISSUE TITLE
hponcfg default path

### ISSUE THREAD

**Issue by kasimon** [seveas/python-hpilo#77]
At least on Debian, hponcfg is installed by the official HP packages to /usr/sbin/hponcfg. It would be really nice if hpilo would find it there out of the box, as this is the only reason I currently have to install /root/.ilo.conf on all my servers. Maybe search in /sbin, /usr/sbin and /usr/local/sbin by default if no path is specified?

**Comment by seveas** [comment]
Good idea!

**Comment by seveas** [comment]
Fixed in dcc5511
