### ISSUE TITLE
hpilo.IloError: Feature not supported - GET_CERT_SUBJECT_INFO

### ISSUE THREAD

**Issue by a31amit** [seveas/python-hpilo#82]
When running get_cert_subject_info() call I am getting ILO error "hpilo.IloError: Feature not supported - GET_CERT_SUBJECT_INFO". I am trying this on HP ILO 4 FW - 2.03 Version. 
Also When I am trying to generate the Customized Certificate for ILO . its output is not valid. 

>>> a.get_cert_subject_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/hpilo.py", line 886, in get_cert_subject_info
  File "build/bdist.macosx-10.10-intel/egg/hpilo.py", line 662, in _info_tag
  File "build/bdist.macosx-10.10-intel/egg/hpilo.py", line 228, in _request
  File "build/bdist.macosx-10.10-intel/egg/hpilo.py", line 547, in _parse_message
hpilo.IloError: Feature not supported - GET_CERT_SUBJECT_INFO

Default Generate of certificate giving me odd output.. 

>>> a.certificate_signing_request()
'-----BEGIN CERTIFICATE REQUEST-----\nMIIDHjCCAgYCAQAwgYkxKDAmBgNVBAMMH21hMi1mNXQtbG5uMDItbW0uY29ycC5h\ncHBsZS5jb20xDDAKBgNVBAsMA0lTUzEgMB4GA1UECgwXSGV3bGV0dC1QYWNrYXJk\nIENvbXBhbnkxEDAOBgNVBAcMB0hvdXN0b24xDjAMBgNVBAgMBVRleGFzMQswCQYD\nVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKrKBuT1s68X\ndm60RREWSgsSEqsZVcQs

==== OUTPUT TRUNCATE ===

**Comment by a31amit** [comment]
I have updated HP ILO 4 to v2.10 still not luck..

**Comment by seveas** [comment]
I'm afraid that `get_cert_subject_info` is an obsolete feature, only supported by iLO2. The certificate request certainly looks valid to me though. What's the problem with it?

**Comment by a31amit** [comment]
ummm.. well by default ILO4 add subject alternative names with hostname which my CA don't allow to sign. it requires only FQDN .. and I didn't find any way to skip SAN's from CSR using ILO GUI and python module. also when I am generating CSR it from python module CA shows that CSR is invalid. as mentioned in previous post output .. 

Is there any way to capture CSR output to proper way ?

**Comment by seveas** [comment]
The SAN issue is not something that is configurable I think, though if you can find an API that lets you do so, I'd love to know about it.

The formatting issue is because you don't print your response properly. Do `print(a.certificate_signing_request())` for a properly formatted CSR.

**Comment by seveas** [comment]
By the way, most people I know use an internal CA for signing iLO certs. As they shouldn't be visible externally anyway, a properly trusted internal CA is cheaper to use.

**Comment by a31amit** [comment]
We are also using internal CA but It's restricted by security policies .. 
I didn't find any API in hp ilo 4 .. even newer REST API for HP ILo seems to be interface to their ssh based console over web service.. http://h20564.www2.hp.com/hpsc/doc/public/display?docId=c04423967

**Comment by seveas** [comment]
I've taken another look at the API, and I'm afraid you'll have to tell your CA to simply ignore the SAN's. There is no way of generating a CSR without them.

**Comment by a31amit** [comment]
Just to add some more notes that HP  ILO4 firmware version 2.54 seems got the feature where someone can exclude or include IP for subject alternative names. By default HP ILO 2.54 version don't include IP address now, only FQDN included.
