### ISSUE TITLE
Firmware update is not easily readable

### ISSUE THREAD

**Issue by ngara** [seveas/python-hpilo#83]
I just jumped from the 2013 to the 2015 version of hpilo and noticed when updating iLO firmware, it looks like this:

Sending request 65536/16784156 bytes (0%)Sending request 131072/16784156 bytes (0%)Sending request 196608/16784156 bytes (1%)Sending request 262144/16784156 bytes (1%)Sending request 327680/16784156 bytes (1%)Sending request 393216/16784156 bytes (2%)Sending request 458752/16784156 bytes (2%)Sending request 524288/16784156 bytes (3%)Sending request 589824/16784156 bytes (3%)Sending request 655360/16784156 bytes (3%) ... etc

It used to delete the old line and print the new one, I believe, so that you would not see the updates all running together in one line.

**Comment by seveas** [comment]
There was a backwards-incompatible change in `update_rib_firmware`. If you use a custom progress function, you now need to do the line-clearing in that function. See hpilo_cli's `print_progress` function for an example.

**Comment by ngara** [comment]
Thanks, it worked!
