### ISSUE TITLE
Dual licensed under GPLv3 and Apache 2.0

### ISSUE THREAD

**Issue by ehsjoar** [seveas/python-hpilo#85]
Due to incompatibility between GPLv3 and Apache 2.0 it is hard to use python-hpilo from, for instance, OpenStack. It would therefore be helpful if the project code could also be released under a more permissive license, like for instance Apache 2.0 (which is how OpenStack is licensed)

**Comment by seveas** [comment]
I'm fine with this, but this needs approval from the other contributors too. Let's see if summoning them works:

@peterfisher
@lotia 
@sspans 
@fragfutter 
@Eagllus 
@ngara
@kevints 
@agy 

You all have contributed at least one patch. Can you please comment to indicate that you approve of dual-licensing your contribution under the Apache 2.0 license?

**Comment by ehsjoar** [comment]
Yes, I didn't go through all the code and just assumed you were the only
copyright holder. Let's see what the other guys say.

Thanks Dennis

// Jonas

**Comment by lotia** [comment]
I'm happy with dual licensing. Let me know if any papers need to be signed and scanned etc.

**Comment by fragfutter** [comment]
fine with me.

**Comment by Eagllus** [comment]
Not sure if it works by replaying to the mail...

But it's fine by me.

**Comment by kevints** [comment]
Fine with me

**Comment by agy** [comment]
I'm more than happy to dual-license (or even change to Apache 2.0).

**Comment by ngara** [comment]
Sounds good to me. 
Nathan

**Comment by ehsjoar** [comment]
Hi Guys,

This is not a quorum yet right? We are still missing 2?

Cheers,

// Jonas

On Wed, Aug 5, 2015 at 10:45 PM, Nathan Garabedian <notifications@github.com
> wrote:

> Sounds good to me.
> Nathan
>
>

**Comment by peterfisher** [comment]
Sounds good to me

**Comment by sspans** [comment]
Looks good to me

**Comment by seveas** [comment]
Thanks everyone! I'll close this issue to stop spamming you. All new releases will be dual GPL/Apache.
