### ISSUE TITLE
exception thrown on 404

### ISSUE THREAD

**Issue by zenfish** [seveas/python-hpilo#86]
A small problem - at least currently the v4 of the firmware isn’t available (the most current version, 2.20, according to your conf) - and it dies with an exception when you try to get all.

You can manually specify the previous one if wanted, of course… but perhaps it should keep trying earlier versions until it finds one or at least dies gracefully instead of keeling over with an unhandled exception? :)  Actually not sure what the correct behavior would be... maybe a flag to get the most-recent avail?

It looks like hpilo_fw.py, in _download, is the culprit with urllib2.

**Comment by seveas** [comment]
HP very rarely actually removes firmware from their FTP server. I've removed it from firmware.conf in 7a3d0cbc (and 2.22 was added in f397f29ab when you reported this).

download_rib_firmware will now handle this gracefully since 2efbeea0
