### ISSUE TITLE
RFE - "all all" or "ALL" or something ;)

### ISSUE THREAD

**Issue by zenfish** [seveas/python-hpilo#87]
Request; it'd be neat if you could get ALL the firmware for a given version or for all... so instead of simply:

$ hpilo_cli download_rib_firmware ilo4 2.10

You could do:

$ hpilo_cli download_rib_firmware ilo4 all

or even:

$ hpilo_cli download_rib_firmware all all

That way you could get a personal mirror of what's out there. I don't know if it's possible to get dates of release automatically, but having that as part of the filename would be awesome as well ;)

**Comment by seveas** [comment]
'ilo4 all' already worked, 'all all' is now implemented in 2efbeea0.
