### ISSUE TITLE
incompatibility with ilo 1.96

### ISSUE THREAD

**Issue by yoshi314** [seveas/python-hpilo#89]
When attempting to upload a certificate ilo-1.96 machine, i get an error 

Sending XML request, 132 bytes
POST /ribcl HTTP/1.1
Host: localhost
Content-Length: 52
Connection: Close

<?xml version="1.0"?>
<RIBCL VERSION="2.0"></RIBCL>
Received 170 bytes

HTTP/1.1 404 Not Found
Content-Type:text/html

<HTML><HEAD><TITLE>Remote Insight</TITLE></HEAD><BODY>
<H1>Request Error</H1>
HTTP/1.1 404 Not Found
</BODY></HTML>
Connecting to 192.168.190.53 port 443
Connecting to 192.168.190.53 port 443
Sending XML request, 1410 bytes
<?xml version="1.0"?>
<RIBCL
 VERSION="2.0"
>
<LOGIN
 PASSWORD="********"
 USER_LOGIN="admin"
>
<RIB_INFO
 MODE="write"
>
<IMPORT_CERTIFICATE
>
-----BEGIN CERTIFICATE-----
(....)
-----END CERTIFICATE-----
</IMPORT_CERTIFICATE>
</RIB_INFO>
</LOGIN>
</RIBCL>

Received 1012 bytes

<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
<INFORM>Scripting utility should be updated to the latest version.</INFORM>
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>
<?xml version="1.0"?>
<RIBCL VERSION="2.22"/>
<RESPONSE
    STATUS="0x0000"
    MESSAGE='No error'
     />
</RIBCL>

Requesting a CSR works fine, though. So i am assuming the functionality is there.

**Comment by seveas** [comment]
I don't actually see an error there. The 404 is the protocol detection that tries an http request, which on iLO1 will fail and this tells the protocol detection logic to use raw sockets. And in the second connection you see that all you get back are the 'No error' messages, which makes me believe the certificate upload worked just fine.

**Comment by yoshi314** [comment]
The certificate was not uploaded, i checked.

However, when i use the script from python-locfg project, i get a confirmation message that everything goes fine, and ilo actually reboots itself and comes up with new certificate.

output of the python-locfg tool run : 

https://gist.github.com/yoshi314/4b125e65d6162c0ac6b5

**Comment by seveas** [comment]
Thanks for that debug info. The XML shown there includes a <reset_rib /> command, so it's not the uploading that resets the iLO, but an explicit reset. Can you try an explicit reset as well?

**Comment by yoshi314** [comment]
Ok, i tried it on another ilo-1 box i found. I got this: 

https://gist.github.com/yoshi314/52ff7ee8a7d3aa036f37

Looks like you were, right. 

Despite those 404 errors and warnings, the new cert is actually installed. It's just that this ilo version does not reload post certificate upload.

**Comment by seveas** [comment]
No version of iLO actually resets itself after a certificate upload, which is just one of the many inconsistencies in the iLO firmware, as for example changing the hostname does reset the iLO. Not much python-hpilo can do about that :smile:

**Comment by yoshi314** [comment]
I think ilo-4 versions i tested actually reboot by default. Could be a configuration option i have not found yet.
