### ISSUE TITLE
Traceback after creating SSL-CSR

### ISSUE THREAD

**Issue by florianschmidt** [seveas/python-hpilo#90]
Hi,

first I really like your lib, it safes me much time. I just noticed when creating a SSL-CSR that the csr is still generated but it drops some error. After takeing a look on your sample code I saw that you allways called certificate_signing_request() without any parameters but parameters are available in the documentation of the function itself.

I guess when you generate the csr without any parameters you get directly the csr with all the HP predifined information (which won't get signed from my CA -> other department)

When you enter your own information’s for generating the csr you don’t get the csr directly but just a message that you can get your csr in around 10 minutes (on iLO4 normally this is much faster -> 30sec are normally sufficient) and have to recall the function later to get the csr. The first call of certificate_signing_request(……) will in this case produce a traceback (but if it is the last line in the code, it doesn’t matter because the csr generation process is started on the iLO) and only the second call after the csr has been generated on the iLO is without errors and warnings.

See traceback of a sample execution:
Traceback (most recent call last):
  File "./ilo-cert.py", line 18, in <module>
    ilo.certificate_signing_request(country="AT", state="Carinthia", locality="Klagenfurt", organization="Infineon Technologies IT-Services GmbH", organizational_unit="IFKL IT OS DC", common_name="vih.infineon.com")
  File "/home/schmiflo/itosdsm/hp-install/.env/gi6-x86_64/lib/python2.7/site-packages/hpilo.py", line 785, in certificate_signing_request
    return self._control_tag('RIB_INFO', 'CERTIFICATE_SIGNING_REQUEST', elements=elements)
  File "/home/schmiflo/itosdsm/hp-install/.env/gi6-x86_64/lib/python2.7/site-packages/hpilo.py", line 690, in _control_tag
    header, message = self._request(root)
  File "/home/schmiflo/itosdsm/hp-install/.env/gi6-x86_64/lib/python2.7/site-packages/hpilo.py", line 225, in _request
    message = self._parse_message(data)
  File "/home/schmiflo/itosdsm/hp-install/.env/gi6-x86_64/lib/python2.7/site-packages/hpilo.py", line 547, in _parse_message
    raise IloError(message, status)
hpilo.IloError: The iLO subsystem is currently generating a Certificate Signing Request(CSR), run script after 10 minutes or more to receive the CSR.

Simple testscript:
#!/usr/bin/env python

from hpilo import Ilo
ilo = Ilo(servername + XXXXXX.com", login="XXXX", password="XXXXXX")  
ilo.certificate_signing_request(country="AT", state="Carinthia", locality="Klagenfurt", organization="Infineon Technologies IT-Services GmbH", organizational_unit="XXXXXX", common_name="XXX.XXXXX.com")

Maybe you can find a solution for this?
Cheers,
Florian

**Comment by seveas** [comment]
Hi Florian,

I actually think the behaviour is ok: there's an exceptional situation, and a certificate_signing_request cannot return a certificate. An exception seems appropriate to me, the calling code can catch it and retry.

What's the behaviour you would expect instead?

**Comment by florianschmidt** [comment]
Hi,

sorry my mistake, I just had a talk with my python Guru @Work and he helped me to clarify how to make an except -> sorry I am more a perl guy and so python is relatively new to me, ticket can be closed, behavior is completely ok!

Thanks!
Florian
