### ISSUE TITLE
set_ers_direct_connect: Invalid HP Passport credentials

### ISSUE THREAD

**Issue by malletp** [seveas/python-hpilo#92]
Hello,

Password are not correctly passed on set_ers_direct_connect. Can you correct it ?

hpilo.py, line 1594
            etree.Element('ERS_HPP_PASSWORD', attrib={'VALUE': str(user_id)}),
replace with
            etree.Element('ERS_HPP_PASSWORD', attrib={'VALUE': str(password)}),

**Comment by seveas** [comment]
Thanks!
Fixed in 3874ff0
