### ISSUE TITLE
update_rib_firmware() : socket.error: [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by Antalis** [seveas/python-hpilo#96]
Hi,
With iLO 1, update_rib_firmware (i test with fw 1.96) causes an exception, it blocks all the time to the value of 65536 bytes : 
Sending request 65536/2097152 bytes (3%)Traceback (most recent call last):
  File "./update_ilo.py", line 65, in <module>
    Main()
  File "./update_ilo.py", line 38, in Main
    ilo.update_rib_firmware(filename=iLO_bin, progress=print_progress)
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 1824, in update_rib_firmware
    return self._request(root, progress)[1]
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 238, in _request
    header, data =  self._communicate(xml, self.protocol, progress=progress)
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 430, in _communicate
    written = sock.write(fw[sent:sent+self.BLOCK_SIZE])
  File "/usr/lib64/python2.7/ssl.py", line 639, in write
    return self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

**Comment by seveas** [comment]
that means it's already failing in the first block (we send 64KB). Can you try changing BLOCK_SIZE in hpilo.py to something smaller and see if that works?

**Comment by Antalis** [comment]
my tests  : 

BLOCK_SIZE = 58 * 1024
    Sending request 59392/2097152 bytes (2%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 1 * 1024
    Sending request 48128/2097152 bytes (2%)Traceback (most recent call last): 
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 30 * 1024
    Sending request 61440/2097152 bytes (2%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 32 * 1024
    Sending request 65536/2097152 bytes (3%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 33 * 1024
    Sending request 67584/2097152 bytes (3%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 39 * 1024
    Sending request 79872/2097152 bytes (3%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 40 * 1024
    Sending request 40960/2097152 bytes (1%)Traceback (most recent call last): 
    socket.error: [Errno 32] Broken pipe

BLOCK_SIZE = 47 * 1024
    Sending request 48128/2097152 bytes (2%)Traceback (most recent call last):
    socket.error: [Errno 32] Broken pipe

**Comment by seveas** [comment]
Hmm, tricky. As HP has stopped supporting iLO 1 and removed documentation for it, I don't know if it's even supposed to work. I think it is, because I think I've tried it. I don't have an iLO1 anymore though, so can't test.

Some more guesses: try with the ILO_LOCAL protocol (which uses hponcfg) and maybe try removing the line that adds a TPM_ENABLED element.

**Comment by Antalis** [comment]
- etree.SubElement(inner, 'TPM_ENABLED', VALUE='Yes')
+ etree.SubElement(inner, 'TPM_ENABLED', VALUE='No')

same problem : 
Sending request 65536/2097152 bytes (3%)Traceback (most recent call last):
  File "./update_ilo.py", line 65, in <module>
    Main()
  File "./update_ilo.py", line 38, in Main
    ilo.update_rib_firmware(filename=iLO_bin, progress=print_progress)
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 1825, in update_rib_firmware
    return self._request(root, progress)[1]
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 238, in _request
    header, data =  self._communicate(xml, self.protocol, progress=progress)
  File "/usr/lib/python2.7/site-packages/hpilo.py", line 430, in _communicate
    written = sock.write(fw[sent:sent+self.BLOCK_SIZE])
  File "/usr/lib64/python2.7/ssl.py", line 639, in write
    return self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe


a method that works with ssh acces : 
cd /map1/firmware
load -source http://host_repo_ilo_ip/ilofw.bin

**Comment by seveas** [comment]
Is there anything in the IML log about these failed firmware updates?

**Comment by Antalis** [comment]
Absolutely nothing.
And after an update by ssh, no more messages in the IML

**Comment by seveas** [comment]
I'm afraid I have to close this issue, as I have no idea what's going wrong and no way to test it, sorry!
